# Generated by Django 5.1.5 on 2025-06-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_profile_photo_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
