# Generated by Django 5.2.3 on 2025-06-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_skill_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
