# Generated by Django 5.2.3 on 2025-06-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_skill_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='goal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
