# Generated by Django 5.1.5 on 2025-06-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_endorsement'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsement',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
